### ISSUE TITLE
help

### ISSUE THREAD

**Issue by maiganne** [INFURA/documentation#4]
hello , i want to get event logs via request https://mainnet.infura.io/pZc5ZTRYM8wYfRPtoQal ,but it returns : requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://mainnet.infura.io/pZc5ZTRYM8wYfRPtoQal

can you help?

**Comment by captDaylight** [comment]
Hey @maiganne, thanks for you question but the best place to ask is our [general support.](https://infura.io/support/ticket)
