### ISSUE TITLE
Documentation doesn't tell how to use API keys

### ISSUE THREAD

**Issue by Xeenych** [INFURA/documentation#48]
Documentation doesn't tell the correct way to interact with Infura and how to send api keys

In an API keys management dashboard the link is^
https://mainnet.infura.io/**v3**/ca39d7ee5da84ff58a9ea74ef5fafb6f

In chapter "Choose a Network" the example is:
https://mainnet.infura.io/your-api-key

Then in REST-Like API section it is:
https://api.infura.io/**v1**/jsonrpc/mainnet/eth_blockNumber?token=YOUR-API-KEY

In JSON_RPC example it is:
https://api.infura.io/**v1**/jsonrpc/mainnet/eth_blockNumber

And in WebSocket it is
wss://mainnet.infura.io/ws

What is a correct way to interact with Infura by REST API and WS

host mainnet.infura.io looks to be down

**Comment by captDaylight** [comment]
@Xeenych We'll have an update soon, stay tuned.

**Comment by vittominacori** [comment]
@captDaylight anyway using both with or without the v3/ path my stats page is empty. 
Is there a minimum time before collected datas are shown in stats dashboard?

**Comment by mbgodsey** [comment]
Documents updated to reflect using the Project ID when sending requests. More information coming soon about Project Secret, Contract Whitelisting, etc.

**Comment by bo-liu** [comment]
> Documents updated to reflect using the Project ID when sending requests. More information coming soon about Project Secret, Contract Whitelisting, etc.

What's the "PROJECT SECRET" used for?  How/When should I use it? Thanks!

**Comment by egalano** [comment]
Hi @bo-liu we've set up a community site for addressing common questions like these in an easily searchable forum. https://community.infura.io.

The answer your specific question is here: https://community.infura.io/t/is-it-ok-to-expose-my-infura-project-id-while-connecting-via-web3js-on-the-client-side/45
>The Project Secret provides another layer of security when sending API requests to Infura. It should only be used when sending requests from a private backend system or server as the Project Secret should never be human readable in your client facing application. There is currently no requirement to use the Project Secret. We will provide more information in future updates and release new documentation to show exactly how the Project Secret can be used when sending requests.
