### ISSUE TITLE
Tell that Infura requires TLS1.2 handshake

### ISSUE THREAD

**Issue by Xeenych** [INFURA/documentation#49]
Looks like Infura requires TLS 1.2 handshake via HTTPS and WSS.
This should be mentioned in documentation.
Not all clients support it.
I've spent several days to figure it out.

**Comment by mbgodsey** [comment]
Thanks for creating this issue, we are treating TLS 1.2 as the standard required protocol. We posted information about this earlier this year on twitter, https://twitter.com/infura_io/status/998678665612361728
