### ISSUE TITLE
API auth flow help needed

### ISSUE THREAD

**Issue by olegabr** [INFURA/documentation#53]
In the `Whats new` section on my https://infura.io/dashboard page I see this warning:

```
JULY 16, 2018
Our developer portal and V3 API auth flow are now live! We are excited to give you more control over sending requests to Infura. The V3 auth flow will become mandatory soon, and we will stop supporting legacy API keys.
```

I'm an author of some [WordPress Ethereum plugins](https://ethereumico.io) that use infura.io and I want to prepare my plugins for that change, but I can not find any information on how to use this new Auth workflow.
Can you point me on it please?

**Comment by egalano** [comment]
Thanks for being proactive @olegabr. Did you already see this blog post? https://blog.infura.io/introducing-the-infura-dashboard-8969b7ab94e7

We are also preparing additional technical documentation which should be on our site within a couple of weeks.

If you have any specific questions I’m happy to help answer them here.

**Comment by olegabr** [comment]
Thank you very much!
Will wait for the documentation announced.
Also, there is a usage pattern to access blockchain data via infura.io API with javascript from the web page on a user side. I assume that it can not be done in the secret key workflow without disclosing the key. What can you advice to overcome this problem?

**Comment by captDaylight** [comment]
@olegabr yes, you can! You _should not_ expose your API secret in your JS client application. Instead, on your Infura project you should white-list specific contracts that your unauthenticated endpoint can access from the client. 

<img width="591" alt="screen shot 2018-11-05 at 1 30 10 pm" src="https://user-images.githubusercontent.com/700617/48018503-ffa33080-e0fe-11e8-9421-ecabbf4c9bbb.png">
